### ISSUE TITLE
How to install stardict-malayalam in ubuntu ?

### ISSUE THREAD

**Issue by jish-44** [indic-dict/stardict-malayalam#1]

**Comment by damooo** [comment]
install `goldendict`. which is opensource dict-viewer.
`sudo apt-get install goldendict`

then download malayalam dictionary files from repository. compiled files are in tars directory in each collection. like
for en-ml dicts here is the folder. inside there will be tar.gz corresponding to each dict. (presently only Olam, wiktionary will be added.)
https://github.com/indic-dict/stardict-malayalam/tree/master/en-head/tars
and `ml-en` dicts tars are in
https://github.com/indic-dict/stardict-malayalam/tree/master/ml-head/tars

download those tars, extract them to a folder, and in goldendict, `edit>dictionaries>add-dictionary`, and choose the locations.
